### ISSUE TITLE
TypeError: bs58check.decode is not a function

### ISSUE THREAD

**Issue by devdudeio** [monkins1010/monkins1010.github.io#4]
Getting this error on the first step when trying to execute the script:

TypeError: bs58check.decode is not a function

I am stuck on the first step here:
[https://monkins1010.github.io/veruslogin/getting-started/#initializing-the-verusid-interface](https://monkins1010.github.io/veruslogin/getting-started/#initializing-the-verusid-interface)

```
import VerusIdInterface from 'verusid-ts-client';
const verusIdClient = new VerusIdInterface('root-system-currency-id', 'http://your-verusd-node.com', {});
```

```
/Users/dude/.yarn/berry/cache/verus-typescript-primitives-https-8477d8e8c3-10c0.zip/node_modules/verus-typescript-primitives/dist/utils/address.js:7
    var payload = bs58check.decode(address);
                            ^

TypeError: bs58check.decode is not a function
    at fromBase58Check (/Users/dude/.yarn/berry/cache/verus-typescript-primitives-https-8477d8e8c3-10c0.zip/node_modules/verus-typescript-primitives/dist/utils/address.js:7:29)
    at Object.<anonymous> (/Users/dude/.yarn/berry/cache/verus-typescript-primitives-https-8477d8e8c3-10c0.zip/node_modules/verus-typescript-primitives/dist/pbaas/ReserveTransfer.js:30:54)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at require$$0.Module._extensions..js (/Users/dude/Desktop/id-server/.pnp.cjs:8156:33)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at require$$0.Module._load (/Users/dude/Desktop/id-server/.pnp.cjs:8004:31)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)

```

```
Node: v20.16.0
Yarn: 4.2.2
OS: MacOS 14.4.1 (M3 CPU)
```

**Comment by Basket123123** [comment]
To install `verus-typescript-primitives' you have to use yarn install else it will use the wrong versions of some dependencies.

**Comment by monkins1010** [comment]
To install verus-typescript-primitives you have to use yarn install else it will use the wrong versions of some dependencies.
